### ISSUE TITLE
bug - cards not always removable when they should be

### ISSUE THREAD

**Issue by mgray35** [cs361fall2017/team13#36]
Every now and then, I've run into situations where a card that should definitely be discard-able cannot be removed. This happened two or three times during my testing last night.

I've attached a couple screenshots of examples. In the first, the 5 of Spades cannot be removed. In the second, the 4 of Diamonds cannot be removed.

![screenshot 2](https://user-images.githubusercontent.com/32281137/32466402-bc90f6dc-c2fb-11e7-87e1-3935baebdbb9.png)
![screenshot 3](https://user-images.githubusercontent.com/32281137/32466401-bc6bfd8c-c2fb-11e7-9f1d-9bac33427ab6.png)

**Comment by kevinkoos** [comment]
fixed in #37

**Comment by mgray35** [comment]
I recall that we came up with a fix for this but the change was not actually implemented. This is still an issue
